languageCode = "en-us"
title = "Hernan Acosta Site"
baseurl = "hernan0216.github.io"
theme = "hugo-theme-nix"

[params]
  GithubID = "hernan0216"
  #GitlabId = "your_gitlab"
  TwitterID = "hernan0216"
  LinkedInID = "acostahernan"
  CvURL = "https://drive.google.com/file/d/1DbrXCxU89VpVQksSnQ8qw8OHpLrptd3e/view?usp=sharing"
  #GoogleplusID = "your_googleplus"
  #FacebookID = "your_facebook"
  Name = "Hernan Acosta"
  HeaderUsername = "hernan0216"
  HeaderHostname = "moon"
  Email = "hernan0216@hotmail.com"
  About = "B.S. in Computer Engineering. My working experience in development started when i was a teenager with C and C++, I woked in a wide range of proyects with diferents technologies, frameworks and programing languajes, my favorite is: Python. I have strong backend developer skills with an OOP aproach using Vim and Tmux like IDE, i worked with a wide range of datastores form relational sql databases, nosql, key value stores and graph stores. I´m mixed with the mind of a Data Scientist and Engineer that belive in Semantic Web and has funny time with Kaggle Machine Learning competitions."
  ProfilePicture = "https://pbs.twimg.com/profile_images/787039731163037696/4r47Y0su.jpg"
  #GoogleAnalytics = "your_google_analytics_id"
