languageCode = "en-us"
title = "Hernan Acosta Site"
baseurl = ""
theme = "hugo-theme-nix"

[params]
  GithubID = "hernan0216"
  LinkedInID = "acostahernan"
  CvURL = "https://raw.githubusercontent.com/hernan0216/hernan.engineer/master/CV.pdf"
  TelegramID = "hernan0216"
  Name = "Hernan Acosta"
  HeaderUsername = "hernan"
  HeaderHostname = "localhost"
  Email = "hernan0216@hotmail.com"
  About = "B.S. in Computer Engineering. My experience as developer started when I was a teenager trying Basic and C. I worked in a wide range of projects with deferents technologies, frameworks and programing languages, my favorite is Python. I have strong backend developer skills with OOP approach using Vim and Tmux as IDE, I worked with a wide range of datastores form relational databases,   document oriented databases, key value stores and graphs. I am a mix between a Data Scientist and Engineer that believe in Semantic Web and enjoy good times with Kaggle Machine Learning competitions."
  ProfilePicture = "https://raw.githubusercontent.com/hernan0216/hernan.engineer/master/0.jpg"
  #GoogleAnalytics = "G-F54XK4D3VQ"
