languageCode = "en-us"
title = "Hernan Acosta Site"
baseurl = "hernan0216.github.io"
theme = "hugo-theme-nix"

[params]
  GithubID = "hernan0216"
  #GitlabId = "your_gitlab"
  TwitterID = "hernan0216"
  LinkedInID = "acostahernan"
  CvURL = "https://s3.us-east-2.amazonaws.com/hernan.engineer/Hernan+Acosta+V2+(en)+(1).pdf"
  #GoogleplusID = "your_googleplus"
  #FacebookID = "your_facebook"
  Name = "Hernan Acosta"
  HeaderUsername = "hernan0216"
  HeaderHostname = "moon"
  Email = "hernan0216@hotmail.com"
  About = "B.S. in Computer Engineering. My working experience in development started when I was a teenager with Basic
and C, I woked in a wide range of proyects with diferents technologies, frameworks and programing languajes, my favorite
now is: Python. I have strong backend developer skills with an OOP aproach using Vim and Tmux as IDE, I worked with a wide range of datastores form relational sql databases, nosql, key value stores and graph stores. I´m mixed with the mind of a Data Scientist and Engineer that belive in Semantic Web and has funny time with Kaggle Machine Learning competitions."
  ProfilePicture = "https://s3.us-east-2.amazonaws.com/hernan.engineer/0.jpg"
  #GoogleAnalytics = "your_google_analytics_id"
