name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: build
      uses: mattbailey/actions-hugo@v0.57.2
      if: github.event.deleted == false
      with:
        args: --gc --minify
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
    - name: Publish Site
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.MY_PERSONAL_TOKEN }}
        # Remember to set this as a secret (i.e. secrets.PERSONAL_TOKEN).
        # Don't forget to set the secret value in the project settings.
        # cname: mysite.com # Or anything else
        # Use if you have a custom domain for your site.
        branch: master # Or anything else
        # Use if your site is not hosted on the gh-pages branch.
        # repo: you/you.github.io
        # Use if your pushing to a different repo.
        # Dont add ".git" to the end of the URL (youl'll get 404s).
        hugoVersion: extended_0.58.3
        # Use if your site requires a specific version of Hugo.
        # Append "extended_" to the begining to use Hugo Extended.
        args: --gc --minify --cleanDestinationDir
        # Use if you want to pass some custom arguments to Hugo.
        # siteDir: /github/workspace/site
        # Use this if your site isn't in the root of your repo.
        # The root of your repo can be found at /github/workspace
